### ISSUE TITLE
Port to GTK+ 3 is in a disconnected fork

### ISSUE THREAD

**Issue by quozl** [richarn/Dictionary-Guarani---Spanish#1]
For your interest, we have a port to GTK+ 3 in this fork;
https://github.com/sugarlabs/spanish-guarani

Let us know if we should make a pull request against your repository.

**Comment by richarn** [comment]
yeah, it looks good

2018-06-26 20:56 GMT-04:00 James Cameron <notifications@github.com>:

**Comment by richarn** [comment]
You should make a pull request

**Comment by quozl** [comment]
Thanks.  I've noted that for developers who were interested in resolving this, and made a fork to _sugarlabs_ organisation to raise awareness.  Please let me know if you have any other Sugar activities that are not yet forked at _sugarlabs_.

**Comment by richarn** [comment]
Thanks, and I don't have others, but I expect to contribute in something again

**Comment by quozl** [comment]
Okay!
